# **Tutorial 01 - Linear Algebra**: Supplementary Interactive Material

-------------------------------------------------------------------------


In [4]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

## Matrix Operations in Python:

Many simple matrix operations are easily implemented in python. Consider, for example:

$$A = \begin{bmatrix} 3 & -2 & 1 \\
4 & 13 & -4 \\
1 & 2 & 3 \end{bmatrix}$$ 

**Define a Matrix**

In [6]:
A = np.array([
    [3, -2,  1],
    [4, 13,  4],
    [1,  2,  3]
])

**Matrix Addition** 


In [7]:
print(A + A)

[[ 6 -4  2]
 [ 8 26  8]
 [ 2  4  6]]


**Transpose**

In [10]:
print(A.T)

[[ 3  4  1]
 [-2 13  2]
 [ 1  4  3]]


**Matrix Inverse**

In [11]:
print(np.linalg.inv(A))

[[ 0.29807692  0.07692308 -0.20192308]
 [-0.07692308  0.07692308 -0.07692308]
 [-0.04807692 -0.07692308  0.45192308]]


**Determinant**

In [12]:
print(np.linalg.det(A))

103.99999999999999


**Decompositions**

In [22]:
QR = np.linalg.qr(A)

In [23]:
print(QR[0]) # Or Q[1] to print R

[[-0.58834841  0.80185231 -0.10430257]
 [-0.78446454 -0.59729815 -0.16688411]
 [-0.19611614 -0.01636433  0.98044412]]


In [25]:
SVD = np.linalg.svd(A)

In [27]:
print(SVD[0]) #Indices 0,1,2 for Sigma, U V^T respectively

[[ 0.04760672  0.92802605 -0.36946076]
 [-0.97688999 -0.03390342 -0.21103673]
 [-0.20837357  0.37096928  0.90496533]]


## Visualizing the P-Norm of the Unit Ball:

We say the unit ball with the p norm as a distance function is:

$$ B_p = \{ x\in R^n ~|~ \|x\|_p \le 1 \}$$
$$\|x\|_p = \left(\sum_{k=1}^n |x_k|^p\right) ^{1/p}$$


In [5]:
x, y   = np.linspace(-1.2, 1.2, 200), np.linspace(-1.2, 1.2, 200) 
X, Y   = np.meshgrid(x, y)          

def p_mask(p, X=X, Y=Y):
    """Return a masked array of ‖(x,y)‖_p, masked outside the unit p-ball."""
    if np.isinf(p):
        P = np.maximum(np.abs(X), np.abs(Y))
    else:
        P = (np.abs(X)**p + np.abs(Y)**p)**(1/p)
        
    return np.ma.masked_where(P > 1.0, P)

p_vals = np.concatenate([[1], np.logspace(0, np.log10(100), 60)]) #NUMBER OF "frames" 

fig, ax = plt.subplots(figsize=(5, 5))
im      = ax.imshow(p_mask(p_vals[0]),
                    extent=[-1.2,1.2,-1.2,1.2],
                    origin='lower',
                    cmap='viridis')
ax.set_aspect('equal')
txt = ax.text(0.02, 0.95, '', transform=ax.transAxes,
              color='black', fontsize=12, ha='left', va='top')

def update(frame):
    p = p_vals[frame]
    im.set_data(p_mask(p))
    txt.set_text(rf'$\|(x,y)\|_{{{p:.2f}}} \leq 1$')
    return im, txt

ani = FuncAnimation(fig, update, frames=len(p_vals),
                    interval=80, blit=True, repeat=True)

plt.close(fig)         
HTML(ani.to_jshtml())   
