# **Tutorial 01 - Linear Algebra**: Supplementary Interactive Material

-------------------------------------------------------------------------


In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

## Matrix Operations in Python:

Many simple matrix operations are easily implemented in python. Consider, for example:

$$A = \begin{bmatrix} 3 & -2 & 1 \\
4 & 13 & -4 \\
1 & 2 & 3 \end{bmatrix}$$ 

**Define a Matrix**

In [2]:
A = np.array([
    [3, -2,  1],
    [4, 13,  4],
    [1,  2,  3]
])

**Matrix Addition** 


In [3]:
print(A + A)

[[ 6 -4  2]
 [ 8 26  8]
 [ 2  4  6]]


**Transpose**

In [4]:
print(A.T)

[[ 3  4  1]
 [-2 13  2]
 [ 1  4  3]]


**Matrix Inverse**

In [5]:
print(np.linalg.inv(A))

[[ 0.29807692  0.07692308 -0.20192308]
 [-0.07692308  0.07692308 -0.07692308]
 [-0.04807692 -0.07692308  0.45192308]]


**Determinant**

In [6]:
print(np.linalg.det(A))

103.99999999999999


# Computing Eigenvalues and Eigenvectors

As you can imagine, given the ability to perform all kinds of matrix operations, we should be able to do some interesting things. Let's try to compute the eigenvalaues, and corresponding eigenvectors of a given matrix! Lets take our matrix A, your first thought may be to think of our usual setup: $$\operatorname{Det}(A - \lambda I) = 0$$

However, python manages to make this quite a big easier for us.


In [7]:
eigenvalues = np.linalg.eigvals(A)

print(eigenvalues)

[13.  4.  2.]


If we want the eigenvalues and eigenvectors, we can instead use:

In [8]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvectors)

[[-1.76090181e-01  9.03539806e-01 -7.07106781e-01]
 [ 9.68495997e-01 -4.25195203e-01  2.19767905e-16]
 [ 1.76090181e-01  5.31494003e-02  7.07106781e-01]]


Now how well does it *actually* work?

In [9]:
v = eigenvectors[:, 0]
lam = eigenvalues[0]

remainder = A @ v - lam * v

print(remainder)

[-2.22044605e-15 -5.32907052e-15 -8.88178420e-16]


## Diagonalization

Recall that a matrix A is diagonalizable if $\exists P,P^{-1},D \text{ s.t } A = PDP^{-1}$ where $D$ is a diagonal matrix. 

Lets go ahead and write a short script in order to determine whether or not it is diagonalizable:

In [11]:

A = np.array([
    [4, 1, 1],
    [0, 2, 1],
    [0, 0, 3]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

P = eigenvectors 

if np.linalg.matrix_rank(eigenvectors) == A.shape[0]:
    D = np.diag(eigenvalues)

    print("A is diagonalizable")
    print("\nP =\n", P)
    print("\nD =\n", D)
    print("\nP^-1 =\n", np.linalg.inv(P))

    # Verify A = P D P^-1
    print("\nReconstructed A =\n", P @ D @ np.linalg.inv(P))
else:
    print("A is not diagonalizable")

A is diagonalizable

P =
 [[ 1.         -0.4472136  -0.81649658]
 [ 0.          0.89442719  0.40824829]
 [ 0.          0.          0.40824829]]

D =
 [[4. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]

P^-1 =
 [[ 1.          0.5         1.5       ]
 [ 0.          1.11803399 -1.11803399]
 [ 0.          0.          2.44948974]]

Reconstructed A =
 [[4. 1. 1.]
 [0. 2. 1.]
 [0. 0. 3.]]


## Visualizing the P-Norm of the Unit Ball:

We say the unit ball with the p norm as a distance function is:

$$ B_p = \{ x\in R^n ~|~ \|x\|_p \le 1 \}$$
$$\|x\|_p = \left(\sum_{k=1}^n |x_k|^p\right) ^{1/p}$$


In [ ]:
x, y   = np.linspace(-1.2, 1.2, 200), np.linspace(-1.2, 1.2, 200) 
X, Y   = np.meshgrid(x, y)          

def p_mask(p, X=X, Y=Y):
    """Return a masked array of ‖(x,y)‖_p, masked outside the unit p-ball."""
    if np.isinf(p):
        P = np.maximum(np.abs(X), np.abs(Y))
    else:
        P = (np.abs(X)**p + np.abs(Y)**p)**(1/p)
        
    return np.ma.masked_where(P > 1.0, P)

p_vals = np.concatenate([[1], np.logspace(0, np.log10(100), 60)]) #NUMBER OF "frames" 

fig, ax = plt.subplots(figsize=(5, 5))
im      = ax.imshow(p_mask(p_vals[0]),
                    extent=[-1.2,1.2,-1.2,1.2],
                    origin='lower',
                    cmap='viridis')
ax.set_aspect('equal')
txt = ax.text(0.02, 0.95, '', transform=ax.transAxes,
              color='black', fontsize=12, ha='left', va='top')

def update(frame):
    p = p_vals[frame]
    im.set_data(p_mask(p))
    txt.set_text(rf'$\|(x,y)\|_{{{p:.2f}}} \leq 1$')
    return im, txt

ani = FuncAnimation(fig, update, frames=len(p_vals),
                    interval=80, blit=True, repeat=True)

plt.close(fig)         
HTML(ani.to_jshtml())   
